# Generated by Django 3.1.6 on 2021-02-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20210217_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
