# Generated by Django 3.1.6 on 2021-02-17 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_party_slug'),
        ('party', '0002_auto_20210217_1106'),
    ]

    operations = [
    ]
