# Generated by Django 3.1.6 on 2021-02-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='owner',
            field=models.CharField(max_length=50),
        ),
    ]
